### ISSUE TITLE
Getting Started instruction failed

### ISSUE THREAD

**Issue by arademaker** [Quetzal-RDF/quetzal#2]
Following the postgresql docker container step-by-step I got the following error:

```
ubuntu@ip-10-253-173-109:~/quetzal/com.ibm.research.quetzal.core/docker/postgresql$ sudo docker build --no-cache --rm -t "ibmresearch/quetzal_postgres"
docker: "build" requires 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build a new image from the source code at PATH
```

**Comment by ksrinivs64** [comment]
You are missing the . at the end to tell the system to look for the Dockerfile in the current directory.  So it should be:
sudo docker build --no-cache --rm -t "ibmresearch/quetzal_postgres" .
