### ISSUE TITLE
Locally cloned code not compiling properly

### ISSUE THREAD

**Issue by amgadmadkour** [Quetzal-RDF/quetzal#4]
After cloning the project to my local machine, If i attempt to import the project into eclipse, i get errors relating to db2jcc4.jar path not set (Seems to be pointing to a specific filesystem path). Even after correcting this path, im getting errors relating to JSONWriter in DumpQuery.java not being found, and others in SparqlParserUtilities.java relating to IbmSparqlAsWalker not being found as well.

I understand that the recommended way for trying out Quetzal is via docker, but i need to modify and deploy it over an existing database and cluster so im interested in getting the locally cloned version working.

**Comment by ksrinivs64** [comment]
Hi we need maven to build from the command line once you clone the code, and then we use the Eclipse Maven plugin to manage it as a Maven project.  So my class path for instance does not have db2jcc.jar.  Can you try that method?

**Comment by amgadmadkour** [comment]
Yes, thanks. This solved my issue.

For anyone who is need of instructions (please feel free to revise or add it to the wiki):

Quetzal includes two sub-projects where one depends on the other. To compile the project outside of docker, first clone the project and run the following command:
- `cd quetzal/com.ibm.research.quetzal.core`
- `mvn install`

Please note that the install command is needed to allow the second sub-project to be compiled. To compile the second project, run the following commands.
- `cd quetzal/rdfstore-server`
- `mvn install`

After compiling the project, the source code can be imported in Eclipse without compilation issues. In order to work with the project under Eclipse, use the import existing project into workspace option. Make sure to revise the project properties for any additional dependencies such as `db2jcc4.jar`.
