### ISSUE TITLE
[Build Fail] IBM mvn repo 

### ISSUE THREAD

**Issue by charbull** [Quetzal-RDF/quetzal#5]
Hello,

Very interesting project, I was hoping to give it a try.
It seems that the mvn repo  not reachable

<id>helix-maven-repo</id>
<url>http://75.126.173.238:8082/nexus/content/groups/public/</url>

for the following dependencies:
    <dependency>
        <groupId>com.ibm.research.hashmvn</groupId>
        <artifactId>hashmvn</artifactId>
        <version>1.1</version>
    </dependency>
    <dependency>
        <groupId>com.ibm.research</groupId>
        <artifactId>iodt.sor</artifactId>
        <version>1.0</version>
    </dependency>

Best,
Charbel

**Comment by ksrinivs64** [comment]
Hello looks like our server went down.  We will attend to this first thing tomorrow and have it up again!

**Comment by charbull** [comment]
Is it possible to publish the 2 jars on mvn central?
I think this dependency com.ibm.wala.util is already there  :)

**Comment by ksrinivs64** [comment]
Ok, server is back up now - will look into adding it into maven central which seems like a longer process.  We've added the pom files and jars into the com.ibm.research.quetzal.core/mvnLibs directory.  Please use maven's method to add local jars into the repository using:
mvn install:install-file -Dfile=<path-to-file> -DpomFile=<path-to-pomfile>
in case the server does not work.

**Comment by charbull** [comment]
Great ! Thank you
