### ISSUE TITLE
IBM Maven Repo

### ISSUE THREAD

**Issue by egyngr** [Quetzal-RDF/quetzal#6]
Hello,

It looks like repository at "http://75.126.173.238:8082/nexus/content/groups/public/" is down. I am failing to download the dependencies. Is there any alternative link that I can get it from?

Thank you for your time!

Regards,

Emre

**Comment by ksrinivs64** [comment]
Hello sorry I was out of the country and just saw this.  Did the issue get resolved because I noticed you closed it.
